name = "htmz"
version = "0.1.2"

description = "A Gleam library for generating HTML"
licences = ["MIT"]
repository = { type = "github", user = "finalclass", repo = "htmz" }

[dependencies]
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.10"
