name = "htmz"
version = "0.1.3"

description = "A Gleam library for generating HTML"
licences = ["MIT"]
repository = { type = "github", user = "finalclass", repo = "htmz" }

[dependencies]
gleam_stdlib = "~> 0.36"

[dev-dependencies]
gleeunit = "~> 1.0"
